const czasowniki = [
    {pl: "zaczynać się", inf: "beginnen", prat: "begann", pzip: "begonnen"},
    {pl: "oferować", inf: "bieten", prat: "bot", pzip: "geboten"},
    {pl: "prosić", inf: "bitten", prat: "bat", pzip: "gebeten"},
    {pl: "zostawać", inf: "bleiben", prat: "blieb", pzip: "geblieben (s.)"},
    {pl: "przynośić", inf: "bringen", prat: "brachte", pzip: "gebracht"},
    {pl: "myśleć", inf: "denken", prat: "dachte", pzip: "gedacht"},
    {pl: "mieć pozwolenie", inf: "dürfen", prat: "durfte", pzip: "gedurft"},
    {pl: "jeść", inf: "essen", prat: "aß", pzip: "gegessen"},
    {pl: "jechać", inf: "fahren", prat: "fuhr", pzip: "gefahren (s.)"},
    {pl: "znajdować", inf: "finden", prat: "fand", pzip: "gefinden"},
    {pl: "latać", inf: "fliegen", prat: "flog", pzip: "geflogen (s.)"},
    {pl: "dawać", inf: "geben", prat: "gab", pzip: "gegeben"},
    {pl: "podobać się", inf: "gefallen", prat: "gefiel", pzip: "gefallen"},
    {pl: "iść", inf: "gehen", prat: "ging", pzip: "gegangen (s.)"},
    {pl: "wygrywać", inf: "gewinnen", prat: "gewann", pzip: "gewonnen"},
    {pl: "mieć", inf: "haben", prat: "hatte", pzip: "gehabt"},
    {pl: "pomagać", inf: "hilfen", prat: "half", pzip: "geholfen"},
    {pl: "znać", inf: "kennen", prat: "kannte", pzip: "gekannt"},
    {pl: "przychodzić", inf: "kommen", prat: "kam", pzip: "gekommen (s.)"},
    {pl: "móc, umieć", inf: "könnte", prat: "konnte", pzip: "gekonnt"},
    {pl: "czytać", inf: "lesen", prat: "las", pzip: "gelesen"},
    {pl: "leżeć", inf: "liegen", prat: "lag", pzip: "gelegen"},
    {pl: "musieć", inf: "müssen", prat: "musste", pzip: "gemusst"},
    {pl: "brać", inf: "nehmen", prat: "nahm", pzip: "genommen"},
    {pl: "wołać, dzwonić", inf: "rufen", prat: "rief", pzip: "gerufen"},
    {pl: "spać", inf: "schlafen", prat: "schlief", pzip: "geschlafen"},
    {pl: "ciąć, kroić", inf: "schneiden", prat: "schnitt", pzip: "geschniteen"},
    {pl: "pisać", inf: "schreiben", prat: "schreib", pzip: "geschreiben"},
    {pl: "pływać", inf: "schwimmen", prat: "schwamm", pzip: "geschwommen (s.)"},
    {pl: "patrzeć", inf: "sehen", prat: "sah", pzip: "gesehen"},
    {pl: "być", inf: "sein", prat: "war", pzip: "gewesen (s.)"},
    {pl: "siedzieć", inf: "sitzen", prat: "saß", pzip: "gesitzen"},
    {pl: "mieć powinność", inf: "sollen", prat: "sollte", pzip: "gesollt"},
    {pl: "mówić", inf: "sprechen", prat: "sprach", pzip: "gesprochen"},
    {pl: "stać", inf: "stehen", prat: "stand", pzip: "gestanden"},
    {pl: "umierać", inf: "sterben", prat: "starb", pzip: "gestorben (s.)"},
    {pl: "spotykać", inf: "treffen", prat: "traf", pzip: "getroffen"},
    {pl: "pić", inf: "trinken", prat: "trank", pzip: "getrunken"},
    {pl: "zapominać", inf: "vergessen", prat: "vergaß", pzip: "vergessen"},
    {pl: "myć", inf: "waschen", prat: "wusch", pzip: "gewaschen"},
    {pl: "zostać, stawać się", inf: "werden", prat: "wurde", pzip: "geworden (s.)"},
    {pl: "wiedzieć", inf: "wissen", prat: "wusste", pzip: "gewusst"},
    {pl: "chcieć", inf: "wollen", prat: "wollte", pzip: "gewollt"},
    // {pl: "", inf: "", prat: "", pzip: ""},
]